In [1]:
import numpy as np
import pdb

In [2]:
det = np.array([2,4])
tra = np.array([2,3,4,2,4])
m = [2, 4]

In [10]:
def spec_metric_mask(cls_list: list, det_labels: np.array, tra_labels: np.array) -> np.array:
    """
    mask matrix, merge all object instance index of the specific class
    :param cls_list: list, valid category list
    :param det_labels: np.array, class labels of detections
    :param tra_labels: np.array, class labels of trajectories
    :return: np.array[bool], True denotes invalid(the object's category is not specific)
    """
    det_num, tra_num = len(det_labels), len(tra_labels)
    metric_mask = np.ones((det_num, tra_num), dtype=bool)
    merge_det_idx = [idx for idx, cls in enumerate(det_labels) if cls in cls_list]
    merge_tra_idx = [idx for idx, cls in enumerate(tra_labels) if cls in cls_list]
    metric_mask[np.ix_(merge_det_idx, merge_tra_idx)] = False
    return metric_mask
def mask_between_boxes(labels_a: np.array, labels_b: np.array):
    """
    :param labels_a: np.array, labels of a collection
    :param labels_b: np.array, labels of b collection
    :return: np.array[bool] np.array , mask matrix, 1 denotes different, 0 denotes same
    """
    mask = labels_a.reshape(-1, 1).repeat(len(labels_b), axis=1) != labels_b.reshape(1, -1).repeat(len(labels_a),
                                                                                                   axis=0)
    return mask

In [17]:
np.logical_or(spec_metric_mask(m, det, tra), mask_between_boxes(det, tra))

array([[False,  True,  True, False,  True],
       [ True,  True, False,  True, False]])

In [18]:
def mask_tras_dets(cls_num, det_labels, tra_labels) -> np.array:
    """
    mask invalid cost between tras and dets
    :return: np.array[bool], [cls_num, det_num, tra_num], True denotes valid (det label == tra label == cls idx)
    """
    det_num, tra_num = len(det_labels), len(tra_labels)
    cls_mask = np.ones(shape=(cls_num, det_num, tra_num)) * np.arange(cls_num)[:, None, None]
    # [det_num, tra_num], True denotes invalid(diff cls)
    same_mask = mask_between_boxes(det_labels, tra_labels)
    # [det_num, tra_num], invalid idx assign -1
    tmp_labels = tra_labels[None, :].repeat(det_num, axis=0)
    tmp_labels[np.where(same_mask)] = -1
    return tmp_labels[None, :, :].repeat(cls_num, axis=0) == cls_mask

In [171]:
vm = mask_tras_dets(5, det, tra)

In [172]:
cost = np.ones((5, len(det), len(tra)))
c = np.arange(10).reshape(2,5)

In [173]:
cost[m] = c

In [191]:
a, b = [1,2], []

In [187]:
cost[0][np.ix_([0, 1], [2, 4])]

array([[1., 1.],
       [1., 1.]])

In [175]:
sad == None

NameError: name 'sad' is not defined

In [178]:
{'two_stage': 1 - two_cost if two_cost is not None else None}

{'two_stage': None}

In [196]:
a = np.array([1,2,4,5])
b = np.array([])
a | b

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [185]:
a = np.concatenate((a, b))

In [192]:
a += b

In [193]:
a

[1, 2]

In [198]:
a.ndim

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [3]:
!pip install jupyter_contrib_nbextensions
!jupyter contrib nbextension install --user
!jupyter nbextension enable execute_time/ExecuteTime

[I 15:22:06 InstallContribNbextensionsApp] jupyter contrib nbextension install --user
[I 15:22:06 InstallContribNbextensionsApp] Installing jupyter_contrib_nbextensions nbextension files to jupyter data directory
[I 15:22:06 InstallContribNbextensionsApp] Installing /home/xiaoyu.li/.conda/envs/polymotv2/lib/python3.7/site-packages/jupyter_contrib_nbextensions/nbextensions/nbTranslate -> nbTranslate
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/nbTranslate/nbTranslate.yaml
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/nbTranslate/languages.js
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/nbTranslate/README.md
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/nbTranslate/demo1.gif
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/sh

[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/runtools/runtools_lock.png
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/runtools/main.js
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/runtools/cellstate.js
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/runtools/main.css
[I 15:22:06 InstallContribNbextensionsApp] - Validating: OK
[I 15:22:06 InstallContribNbextensionsApp] Installing /home/xiaoyu.li/.conda/envs/polymotv2/lib/python3.7/site-packages/jupyter_contrib_nbextensions/nbextensions/splitcell -> splitcell
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/splitcell/splitcell.yaml
[I 15:22:06 InstallContribNbextensionsApp] Up to date: /home/xiaoyu.li/.local/share/jupyter/nbextensions/splitcell/icon.p

Enabling notebook extension execute_time/ExecuteTime...
      - Validating: OK


In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])