In [1]:
import numpy as np
from pyquaternion import Quaternion

In [2]:
q1 = Quaternion(axis=(0, 0, 1), radians=1).q

In [3]:
q2 = np.mat(q1).T

In [43]:
q3 = np.array(q2.T.tolist()[0])

In [45]:
np.append(q1, q3)

array([0.87758256, 0.        , 0.        , 0.47942554, 0.87758256,
       0.        , 0.        , 0.47942554])

In [4]:
q2

matrix([[0.87758256],
        [0.        ],
        [0.        ],
        [0.47942554]])

In [5]:
q2[-1, 0] -= np.pi

In [6]:
q2

matrix([[ 0.87758256],
        [ 0.        ],
        [ 0.        ],
        [-2.66216711]])